name: ffloat_example
description: Demonstrates how to use the ffloat plugin.
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  fbutton_nullsafety: ^5.0.0
  ffloat:
    path: ../
  flutter:
    sdk: flutter
  fradio_nullsafety: ^2.0.2
  fsuper: ^2.1.1
  fswitch_nullsafety: ^2.0.2

dependency_overrides: {}

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/
  uses-material-design: true
